ALTER TABLE "users" ADD COLUMN "cv_counter" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "users" ADD COLUMN "cv_counter_max" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "users" ADD COLUMN "cl_counter" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "users" ADD COLUMN "cl_counter_max" INTEGER NOT NULL DEFAULT 0;
